openapi: 3.0.3
info:
  title: Hellena API
  description: Service for retrieval disounts info from local stores
  version: 0.0.1
servers:
  - url: https://localhost:8080/v1
    description: Local server
  - url: https://mysterious-dusk-84277.herokuapp.com/v1
    description: Main (production) server
tags:
  - name: "init"
paths:
  /item/all:
    summary: Item endpoint
    description: Place that holds all item operations
    get:
      tags:
        - get
      summary: Return a list of items
      operationId: getItems
      responses:
        '200':
          description: A JSON array of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/itemDto'
  /item/search:
    summary: Item search endpoint
    description: Search items include paggination and sort support
    get:
      operationId: searchItems
      parameters:
        - name: query
          in: query
          required: true
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/searchItemDto'
      responses:
        '200':
          description: A JSON array of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/itemDto'
  /item/category/all:
    get:
      summary: Return list of item's categories
      operationId: getCategories
      responses:
        '200':
          description: A JSON arry of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/categoryDto'
components:
  schemas:
    sortDto:
      type: object
      properties:
        name:
          type: string
        direction:
          type: string
          enum:
            - asc
            - desc
    pageDto:
      type: object
      properties:
        index:
          type: number
        size:
          type: number
        sort:
          type: array
          items:
            $ref: '#/components/schemas/sortDto'
    itemDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        storeName:
          type: string
        orginalPrice:
          type: number
        actionPrice:
          type: number
    searchItemDto:
      type: object
      properties:
        name:
          type: string
        categoryId:
          type: number
        cityId:
          type: number
        priceMIn:
          type: number
        priceMax:
          type: number
        page:
          type: object
          $ref: '#/components/schemas/pageDto'
    categoryDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
