openapi: 3.0.3
info:
  title: Hellena API
  description: Application for predicting the results of football matches.
  version: 0.0.1
servers:
  - url: https://mysterious-dusk-84277.herokuapp.com/v1
    description: Main (production) server
tags:
  - name: "init"
paths:
  /match/list:
    get:
      summary: Returns a list of matches.
      operationId: getUsers
      responses:
        '200':
          description: A JSON array of football matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/matchDto'
  /item/all:
    get:
      summary: Return a list of items
      operationId: getItems
      responses:
        '200':
          description: A JSON array of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/itemDto'
components:
  schemas:
    matchDto:
      type: object
      properties:
        home:
          type: string
        guest:
          type: string
        oodDto:
          type: object
          $ref: '#/components/schemas/oodDto'
        matchDay:
          type: string
        created:
          type: string
    oodDto:
      type: object
      properties:
        tip_1:
          type: number
        tip_X:
          type: number
        tip_2:
          type: number
        tip_1X:
          type: number
        tip_X2:
          type: number
        tip_12:
          type: number
    itemDto:
      type: object
      properties:
        name:
          type: string
        storeName:
          type: string
        orginalPrice:
          type: number
        actionPrice:
          type: number
